### ISSUE TITLE
Not working anymore. I fixed a couple of issues but still fails

### ISSUE THREAD

**Issue by quizzical86** [lukas-hetzenecker/home-assistant-zyxel-poe#1]
Dear Lukas,
Any chance you could update this integration?
I managed to solve a couple of issues:
* Home Assistant nowadays requires a manifest.json file. I create one that works (in annex).
* I think the "__init__.py" file needs to contain the version number as well (done in annex).
* The switch.py file on two occasions referred to a SwitchDevice which I had to replace with SwitchEntity

Unfortunately I didn't get any further than that and the log creates an error "Cannot load Zyxel data:"

[zyxel_poe.zip](https://github.com/lukas-hetzenecker/home-assistant-zyxel-poe/files/8458951/zyxel_poe.zip)

**Comment by quizzical86** [comment]
I would still love to get this working if possible ☺️

**Comment by lukas-hetzenecker** [comment]
Hello @quizzical86 - could you try the latest changes?
With those it is working for me on Home Assistant 2022.8.2

But please keep in mind I could only test it with a ZyXEL GS1900-10HP (already a fairly old model). As this is based on Web-Scraping, there will surely be incompatibilities with other models.

**Comment by quizzical86** [comment]
Thanks a lot!
I'm using the same model  (just an 8-port version so the Zyxel GS1900-8HP).

I tried with the latest changes but got these errors:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/zyxel_poe/switch.py", line 86, in async_setup_platform
    await poe_data.async_update()
  File "/config/custom_components/zyxel_poe/switch.py", line 210, in _async_update
    await self._login()
  File "/config/custom_components/zyxel_poe/switch.py", line 167, in _login
    await self._login(is_retry=True)
  File "/config/custom_components/zyxel_poe/switch.py", line 165, in _login
    raise Exception("Login failed: %s" % ret2.text)
NameError: name 'ret2' is not defined`

I'm on the latest firmware (V2.70), are you as well?
I understand you are partially basing yourself on code from someone else and as you can see here (https://github.com/jonbulica99/zyxel-poe-manager/issues/4) that person has recently revamped his code because the login process has changed with V2.70).

**Comment by quizzical86** [comment]
@lukas-hetzenecker The error I get is indeed specific to the older version of the 'zyxel Poe manager' project for older firmware versions.
I assume you are then still on V2.60 or 2.50?
V2.70 fixed quite a number of security vulnerabilities on the GS1900, so that's why I installed it.

I'm quite satisfied that ZyXEL still cares about the security of their older products ^_^

**Comment by quizzical86** [comment]
@lukas-hetzenecker I've been trying to compare https://github.com/jonbulica99/zyxel-poe-manager/issues/4 old (for V2.50) and new (for 2.70) code and implement the changes in your code, in order to make it work with the latest firmware.

It looks like you had to make quite extensive changes to the code to make it work with Home Assistant. In the beginning I was able to make the changes but as I advanced further into the code it became too complex (I don't understand the code at all, I'm an economist :-P so just trying to apply logical thinking) so I didn't succeed.

I tried the alternative option of downgrading the firmware (which I wanted to avoid given that I'm reintroducing security vulnerabilities). In the backup I have V2.00 so I switched to that, but that created a messy situation where my switch is now on V2.00 but I can't login anymore using my login & password (nor the default one) and I'll have to factory reset my switch when I get back home in a couple of weeks... Anyhow it was probably a useless attempt as I assume you're on V2.50 right?
On Zyxel's website I can only go back as far as 2.60(AAHI.3)C0 so can't get my hands on V2.50 (which I guess makes sense as that version is already 3 years old).
I found V2.30 on some random looking spansih website but not really trusting that.

**Comment by quizzical86** [comment]
@lukas-hetzenecker believe it or not but with the mess I had with my zyxel switch it somehow destroyed one of my POE camera's so I'll have to buy a new one... :(
anyhow my switch is now back in working order. My plan B is to downgrade to the same older firmware that you are using (even if it opens up vulnerabilities). Could you let me know which version you are using? I will then contact Zyxel support and ask them whether they can send it to me.

**Comment by lukas-hetzenecker** [comment]
@quizzical86 sorry again for the very late reply, unfortunately I don't find much time to maintain this project currently.
At least I could now check the firmware of the switch. Bad news, I'm on an even older release: V2.40(AAZI.1)_20180705
These devices are running in a place I don't get to too often these days. 
I will try to upgrade the firmware next time I'm on a visit if I find some time for it (should already be in a few weeks), and then check whether I can get integration working again. But I'm not brave enough to attempt the firmware upgrade remotely.

**Comment by lukas-hetzenecker** [comment]
okay, change of plans: I had two GS1900-10HP devices at that location, for one of them I don't care too much about a downtime. Updated this one to V2.70(AAZI.3), can reproduce the problem, and try to fix it

**Comment by lukas-hetzenecker** [comment]
I've now published a new release which should be compatible with firmware version 2.70 (tested successfully on my two devices)
